### ISSUE TITLE
bug: useResizeContainer - The parent DOM element of the data grid has an empty width.

### ISSUE THREAD

**Issue by martinjrobins** [pkpdapp-team/pkpdapp#399]
When I login and am at the list of projects, once I select a project I get the following error in the console:

```
MUI: useResizeContainer - The parent DOM element of the data grid has an empty width.
Please make sure that this element has an intrinsic width.
The grid displays with a width of 0px.

More details: https://mui.com/r/x-data-grid-no-dimensions. 
    at GridBody (http://localhost:3000/static/js/bundle.js:68038:5)
    at div
    at http://localhost:3000/static/js/bundle.js:22238:66
    at GridRoot (http://localhost:3000/static/js/bundle.js:72193:100)
    at GridContextProvider (http://localhost:3000/static/js/bundle.js:76754:3)
    at DataGrid (http://localhost:3000/static/js/bundle.js:64894:84)
    at div
    at http://localhost:3000/static/js/bundle.js:22238:66
    at Box (http://localhost:3000/static/js/bundle.js:61606:72)
    at div
    at http://localhost:3000/static/js/bundle.js:22238:66
    at Box (http://localhost:3000/static/js/bundle.js:61606:72)
    at Data (http://localhost:3000/static/js/bundle.js:5111:72)
    at div
    at http://localhost:3000/static/js/bundle.js:22238:66
    at Box (http://localhost:3000/static/js/bundle.js:61606:72)
    at div
    at TabPanel (http://localhost:3000/static/js/bundle.js:9401:5)
    at div
    at MainContent (http://localhost:3000/static/js/bundle.js:9432:72)
    at main
    at http://localhost:3000/static/js/bundle.js:22238:66
    at Box (http://localhost:3000/static/js/bundle.js:61606:72)
    at div
    at http://localhost:3000/static/js/bundle.js:22238:66
    at Box (http://localhost:3000/static/js/bundle.js:61606:72)
    at Sidebar (http://localhost:3000/static/js/bundle.js:9661:78)
    at App (http://localhost:3000/static/js/bundle.js:1228:78)
    at Provider (http://localhost:3000/static/js/bundle.js:387751:3)
```

**Comment by eatyourgreens** [comment]
I’m not 100% sure, but I think this is happening because the Data tab is hidden when a project first loads, so the data grids for protocols and observations are both inside a zero-width container.
